INSERT INTO PESSOA(NOME, SEXO, EMAIL, DATA_NASCIMENTO, NATURALIDADE, NACIONALIDADE, CPF, SENHA, DATA_INCLUSAO, DATA_ALTERACAO) VALUES('Kafika', 'FEMININO', 'karfica@mail.com', '1993-01-31', 'Brasília', 'Brasil','26486888032', '123', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );

INSERT INTO PESSOA(NOME, SEXO, EMAIL, DATA_NASCIMENTO, NATURALIDADE, NACIONALIDADE, CPF, SENHA, DATA_INCLUSAO, DATA_ALTERACAO) VALUES('João', 'MASCULINO', 'joao@mail.com', '1964-03-12', 'Brasília', 'Brasil','80740079018', '123', CURRENT_TIMESTAMP , CURRENT_TIMESTAMP );

INSERT INTO PESSOA(NOME, SEXO, EMAIL, DATA_NASCIMENTO, NATURALIDADE, NACIONALIDADE, CPF, SENHA, DATA_INCLUSAO, DATA_ALTERACAO) VALUES('Maria', 'FEMININO', 'maria@mail.com', '1984-01-31', 'Brasília', 'Brasil','21619667070', '123' , CURRENT_TIMESTAMP , CURRENT_TIMESTAMP );
